# 3 hours
default-cache-ttl 10800
# 12 hours
max-cache-ttl 43200

# Facilitate SSH.  Specify pinentry-curses to avoid the issue of screen
# sessions sending GTK windows to the local X11 session.  Specify a wrapper
# with a built-in pause to allow the remote user to minimize the keyboard if on
# a phone.
pinentry-program ~/bin/pinentry-curses-with-pause
