# 3 hours
default-cache-ttl 10800
# 12 hours
max-cache-ttl 43200

# Facilitate SSH.  Specify pinentry-curses to avoid the issue of screen
# sessions sending GTK windows to the local X11 session.  Specify a wrapper
# with a built-in pause to allow the remote user to minimize the keyboard if on
# a phone.

# pinentry selection poses several problems.  
#
# In an SSH session, it is typically not possible to use pinentry-gtk-2.
#
# When operating in the background (like when attempting to handle certain
# types of links for the browser), it is not possible to use pinentry-curses.
#
# I think pinentry-gtk-2 will fall back to pinentry-curses depending $(tty),
# ${GPG_TTY}, and/or ${TERM} ... or maybe ${DISPLAY}.  (RTFM and get more sure
# about how that works.)  That mostly handles both cases above.
#
# screen sessions can start in a good position to use pinentry-gtk-2, but may
# be accessed remotely, with no change to the appropriate variables.
# Configuration is necessary to make pinentry always select a curses option
# when screen is detected.
#
# Small screens present one more problem.  If a phone is used to connect by
# SSH, pinentry-curses will fail due to lack of screen real estate.  This can
# be resolved with a brief pause, allowing time for the user to minimize the
# keyboard.  A wrapper script can handle that.
#
# The wrapper script below should handle the pause, and it should decide
# whether pinentry-gtk-2 or pinentry-curses should be used.

pinentry-program ~/bin/pinentry-wrapper
