-- Comments look like this.  The whole file is Lua.


conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'f0fff0',
    default_graph_height = 30,
    default_outline_color = 'ff0000',
    default_shade_color = 'ff0000',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 0,
    gap_y = 0,
    minimum_height = 1440,
    maximum_height = 1440,
    minimum_width = 2550,
    maximum_width = 2550,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    out_to_wayland = false,
    own_window = false,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    show_graph_range = true,
    show_graph_scale = true,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

-- Tabs can be used to create columns with variable width text.  Graphs with no
-- width parameter fill the remainder of the line.  Multiple graphs per line
-- seem to overflow the line.
--
-- I have the CPU graphs in a 4x4 grid, using fixed widths.  That will only
-- look right on one screen resolution.  Find a better way to make columns out
-- of graphs, if possible.


conky.text = [[

[${color ff0100}${scroll 1 *}$color] $uptime

storage:
  / ${tab 100}${fs_used /}${tab 160}/${tab 20}${fs_size /} ${tab 250}(${fs_used_perc /}%) ${tab 100}${fs_bar /}
  /boot ${tab 100}${fs_used /boot}${tab 160}/${tab 20}${fs_size /boot} ${tab 250}(${fs_used_perc /boot}%) ${tab 100}${fs_bar /boot}
  /boot/efi ${tab 100}${fs_used /boot/efi}${tab 160}/${tab 20}${fs_size /boot/efi} ${tab 250}(${fs_used_perc /boot/efi}%) ${tab 100}${fs_bar 6,2390 /boot/efi}
  /usr ${tab 100}${fs_used /usr}${tab 160}/${tab 20}${fs_size /usr} ${tab 250}(${fs_used_perc /usr}%) ${tab 100}${fs_bar /usr}
  /var ${tab 100}${fs_used /var}${tab 160}/${tab 20}${fs_size /var} ${tab 250}(${fs_used_perc /var}%) ${tab 100}${fs_bar /var}
  /var/log ${tab 100}${fs_used /var/log}${tab 160}/${tab 20}${fs_size /var/log} ${tab 250}(${fs_used_perc /var/log}%) ${tab 100}${fs_bar /var/log}
  /var/cache ${tab 100}${fs_used /var/cache}${tab 160}/${tab 20}${fs_size /var/cache} ${tab 250}(${fs_used_perc /var/cache}%) ${tab 100}${fs_bar /var/cache}
  /var/tmp ${tab 100}${fs_used /var/tmp}${tab 160}/${tab 20}${fs_size /var/tmp} ${tab 250}(${fs_used_perc /var/tmp}%) ${tab 100}${fs_bar /var/tmp}
  /home ${tab 100}${fs_used /home}${tab 160}/${tab 20}${fs_size /home} ${tab 250}(${fs_used_perc /home}%) ${tab 100}${fs_bar /home}

  SSD read ${tab 100}${diskio_read /dev/nvme0n1}
  ${diskiograph_read /dev/nvme0n1}   
  SSD write ${tab 100}${diskio_write /dev/nvme0n1}
  ${diskiograph_write /dev/nvme0n1}   

network:

  WiFi receive ${tab 100}${downspeed wlan0}
  ${downspeedgraph wlan0}   
  WiFi send ${tab 100}${upspeed wlan0}
  ${upspeedgraph wlan0}   

memory:
  RAM usage: ${tab 100}${mem}${tab 160}/${tab 20}${memmax} ${tab 250}(${memperc}%) ${tab 100}${membar 4}
  swap usage: ${tab 100}${swap}${tab 160}/${tab 20}${swapmax} ${tab 250}(${swapperc}%) ${tab 100}${swapbar 4}

processing:

  processes:
    total: ${tab 100}${processes}  
    running: ${tab 100}${running_processes}

  CPU
    ${cpugraph cpu1 20,620} ${cpugraph cpu2 20,620} ${cpugraph cpu3 20,620} ${cpugraph cpu4 20,620}
    ${cpugraph cpu5 20,620} ${cpugraph cpu6 20,620} ${cpugraph cpu7 20,620} ${cpugraph cpu8 20,620}
    ${cpugraph cpu9 20,620} ${cpugraph cpu10 20,620} ${cpugraph cpu11 20,620} ${cpugraph cpu12 20,620}
    ${cpugraph cpu13 20,620} ${cpugraph cpu14 20,620} ${cpugraph cpu15 20,620} ${cpugraph cpu16 20,620}

OS update status: ${tab 100}${tail /var/log/update_debian.ret 1}
]]
